# Generated by Django 4.0.3 on 2022-03-19 08:40

import apps.main.models.posts
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=50, verbose_name='Электронная почта')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('video_url', models.CharField(help_text='url для скачивания видео с тг', max_length=255, verbose_name='')),
                ('video', models.FileField(null=True, upload_to=apps.main.models.posts.get_video_upload_path, verbose_name='Видео')),
                ('is_download', models.BooleanField(default=False, verbose_name='Видео скачено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('tg_user', models.ForeignKey(help_text='ID пользователя тг', on_delete=django.db.models.deletion.CASCADE, related_name='video_posts', to='users.tguser')),
            ],
            options={
                'verbose_name_plural': 'Видео посты',
                'db_table': 'video_posts',
            },
        ),
    ]
